robot_interface:
  ros__parameters:
    robot_yaml_path: "/home/pepms/wsros2/mpc-ws/src/odri_ros2/odri_examples/config/robots/separate_legs.yaml"
    adapter_name: "enp61s0"
    n_slaves: 1
    safe_configuration: [-2.42738, 1.33908]
    safe_torque: 0.5
    safe_kp: 0.5
    safe_kd: 5.0
    safe_current: 5.0

