robot_interface:
  ros__parameters:
    robot_yaml_path: "/home/pepms/wsros2/mpc-ws/src/odri_ros2/odri_examples/config/robots/separate_legs.yaml"
    adapter_name: "enp61s0"
    n_slaves: 1
    safe_configuration: [-3.06511, 1.41166]
    safe_kp: 0.5
    safe_kd: 5.0
